### ISSUE TITLE
can't load mod

### ISSUE THREAD

**Issue by SimonBolski** [atenfyr/bettertaxes#8]
Hi, 

I just wanted to try out this mod, but every time I try to load it a get an error.
I can't seem to figure out the problem just my looking at the logs. 
[client.log](https://github.com/atenfyr/bettertaxes/files/3465260/client.log)

tried to reload the mods a couple of times, also restarting the game doesn't help.

**Comment by atenfyr** [comment]
I've released BetterTaxes 2.1.1 which should solve the issue. Let me know if it doesn't.
